test_that("R drives Python end to end", {
  skip_if_not(nzchar(Sys.which("python")) || nzchar(Sys.getenv("RPYTHON_PYTHON")), "no python on PATH")
  py <- tryCatch(python(), error = function(e) NULL)
  skip_if(is.null(py), "python worker with rpython not available")
  on.exit(py$close())
  expect_equal(py$run("1 + 1"), 2)
  np <- py$package("numpy")
  expect_equal(np$arange(3L), 0:2)
  df <- data.frame(x = c(1.5, NA), f = factor(c("a", "b"), ordered = TRUE))
  py$assign("df", df)
  expect_true(py$run("df['f'].cat.ordered"))
  back <- py$get("df")
  expect_identical(back$f, df$f)
  py$assign("rf", function(x) x * 10)
  expect_equal(py$run("rf(4.0)"), 40)
  expect_error(py$run("1/0"), "ZeroDivisionError")
})
